.PHONY: concurrency-mini-project
concurrency-mini-project:
	go run cmd/workerpool/main.go 2 100 200 300


.PHONY: http_simple_server_with_context
http_simple_server_with_context:
	go run cmd/http_simple_server_with_context/main.go
