.PHONY: concurrency-mini-project
concurrency-mini-project:
	go run cmd/workerpool/main.go 2 100 200 300


.PHONY: http_simple_server_with_context
http_simple_server_with_context:
	go run cmd/http_simple_server_with_context/main.go


.PHONY: task103
task103:
	go run cmd/task103/main.go

.PHONY: task103ok
task103ok:
	go run cmd/task103ok/main.go