// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecases

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"notesv1/internal/apps/notes/dto"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateNote provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateNote(ctx context.Context, note dto.CreateNoteCommand) (dto.CreateNoteResult, error) {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 dto.CreateNoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateNoteCommand) (dto.CreateNoteResult, error)); ok {
		return returnFunc(ctx, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateNoteCommand) dto.CreateNoteResult); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Get(0).(dto.CreateNoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateNoteCommand) error); ok {
		r1 = returnFunc(ctx, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockRepository_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - note dto.CreateNoteCommand
func (_e *MockRepository_Expecter) CreateNote(ctx any, note any) *MockRepository_CreateNote_Call {
	return &MockRepository_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, note)}
}

func (_c *MockRepository_CreateNote_Call) Run(run func(ctx context.Context, note dto.CreateNoteCommand)) *MockRepository_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateNoteCommand
		if args[1] != nil {
			arg1 = args[1].(dto.CreateNoteCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateNote_Call) Return(createNoteResult dto.CreateNoteResult, err error) *MockRepository_CreateNote_Call {
	_c.Call.Return(createNoteResult, err)
	return _c
}

func (_c *MockRepository_CreateNote_Call) RunAndReturn(run func(ctx context.Context, note dto.CreateNoteCommand) (dto.CreateNoteResult, error)) *MockRepository_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteNote(ctx context.Context, q dto.DeleteNoteCommand) (dto.DeleteNoteResult, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 dto.DeleteNoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DeleteNoteCommand) (dto.DeleteNoteResult, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DeleteNoteCommand) dto.DeleteNoteResult); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(dto.DeleteNoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.DeleteNoteCommand) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockRepository_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - q dto.DeleteNoteCommand
func (_e *MockRepository_Expecter) DeleteNote(ctx any, q any) *MockRepository_DeleteNote_Call {
	return &MockRepository_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, q)}
}

func (_c *MockRepository_DeleteNote_Call) Run(run func(ctx context.Context, q dto.DeleteNoteCommand)) *MockRepository_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.DeleteNoteCommand
		if args[1] != nil {
			arg1 = args[1].(dto.DeleteNoteCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteNote_Call) Return(deleteNoteResult dto.DeleteNoteResult, err error) *MockRepository_DeleteNote_Call {
	_c.Call.Return(deleteNoteResult, err)
	return _c
}

func (_c *MockRepository_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, q dto.DeleteNoteCommand) (dto.DeleteNoteResult, error)) *MockRepository_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetNote provides a mock function for the type MockRepository
func (_mock *MockRepository) GetNote(ctx context.Context, q dto.GetNoteQuery) (dto.GetNoteResult, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 dto.GetNoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetNoteQuery) (dto.GetNoteResult, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetNoteQuery) dto.GetNoteResult); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(dto.GetNoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetNoteQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNote'
type MockRepository_GetNote_Call struct {
	*mock.Call
}

// GetNote is a helper method to define mock.On call
//   - ctx context.Context
//   - q dto.GetNoteQuery
func (_e *MockRepository_Expecter) GetNote(ctx any, q any) *MockRepository_GetNote_Call {
	return &MockRepository_GetNote_Call{Call: _e.mock.On("GetNote", ctx, q)}
}

func (_c *MockRepository_GetNote_Call) Run(run func(ctx context.Context, q dto.GetNoteQuery)) *MockRepository_GetNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetNoteQuery
		if args[1] != nil {
			arg1 = args[1].(dto.GetNoteQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetNote_Call) Return(getNoteResult dto.GetNoteResult, err error) *MockRepository_GetNote_Call {
	_c.Call.Return(getNoteResult, err)
	return _c
}

func (_c *MockRepository_GetNote_Call) RunAndReturn(run func(ctx context.Context, q dto.GetNoteQuery) (dto.GetNoteResult, error)) *MockRepository_GetNote_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotes provides a mock function for the type MockRepository
func (_mock *MockRepository) ListNotes(ctx context.Context, q dto.ListNotesQuery) (dto.ListNotesResult, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for ListNotes")
	}

	var r0 dto.ListNotesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListNotesQuery) (dto.ListNotesResult, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListNotesQuery) dto.ListNotesResult); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(dto.ListNotesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListNotesQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotes'
type MockRepository_ListNotes_Call struct {
	*mock.Call
}

// ListNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - q dto.ListNotesQuery
func (_e *MockRepository_Expecter) ListNotes(ctx any, q any) *MockRepository_ListNotes_Call {
	return &MockRepository_ListNotes_Call{Call: _e.mock.On("ListNotes", ctx, q)}
}

func (_c *MockRepository_ListNotes_Call) Run(run func(ctx context.Context, q dto.ListNotesQuery)) *MockRepository_ListNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListNotesQuery
		if args[1] != nil {
			arg1 = args[1].(dto.ListNotesQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListNotes_Call) Return(listNotesResult dto.ListNotesResult, err error) *MockRepository_ListNotes_Call {
	_c.Call.Return(listNotesResult, err)
	return _c
}

func (_c *MockRepository_ListNotes_Call) RunAndReturn(run func(ctx context.Context, q dto.ListNotesQuery) (dto.ListNotesResult, error)) *MockRepository_ListNotes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateNote(ctx context.Context, q dto.UpdateNoteCommand) (dto.UpdateNoteResult, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 dto.UpdateNoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateNoteCommand) (dto.UpdateNoteResult, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateNoteCommand) dto.UpdateNoteResult); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(dto.UpdateNoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UpdateNoteCommand) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockRepository_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - q dto.UpdateNoteCommand
func (_e *MockRepository_Expecter) UpdateNote(ctx any, q any) *MockRepository_UpdateNote_Call {
	return &MockRepository_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, q)}
}

func (_c *MockRepository_UpdateNote_Call) Run(run func(ctx context.Context, q dto.UpdateNoteCommand)) *MockRepository_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdateNoteCommand
		if args[1] != nil {
			arg1 = args[1].(dto.UpdateNoteCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateNote_Call) Return(updateNoteResult dto.UpdateNoteResult, err error) *MockRepository_UpdateNote_Call {
	_c.Call.Return(updateNoteResult, err)
	return _c
}

func (_c *MockRepository_UpdateNote_Call) RunAndReturn(run func(ctx context.Context, q dto.UpdateNoteCommand) (dto.UpdateNoteResult, error)) *MockRepository_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}
